spring:
  application:
    name: auth-microservice
  security:
    user:
      name: admin
      password:
    basic:
      enabled: false
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
external-service:
  url: "http://auth-vivelibre:8080/token"
  credentials:
    username: "auth-vivelibre"
    password: "password"